version: '3.9'

services:
  srs:
    image: ossrs/srs:5
    container_name: srs
    restart: always
    ports:
      - 1935:1935
      - 1985:1985
      - 8080:8080
      - 8000:8000
      - 8000:8000/udp
    environment:
      - CANDIDATE=$CANDIDATE
    command: ./objs/srs -c conf/rtmp2rtc.conf