version: '3.9'

services:
  db:
    image: mariadb
    container_name: mariadb
    volumes:
      - /home/mariadb/data:/var/lib/mysql:rw
    restart: always
    networks:
      - traefik
    environment:
      MYSQL_ROOT_PASSWORD: chevereto_root
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASS: chevereto

  chevereto:
    depends_on:
      - db
    image: nmtan/chevereto:1.6.2
    container_name: chevereto
    restart: always
    networks:
      - traefik
    environment:
      CHEVERETO_DB_HOST: db
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_DB_PASS: chevereto
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_DB_PREFIX: chv_
    volumes:
      - /OneDrive/chevereto:/var/www/html/images:rw
      - /home/chevereto/upload.ini:/usr/local/etc/php/conf.d/upload.ini:ro
      - /home/chevereto/1.6.2:/var/www/html:rw
    # ports:
    #   - 1066:80
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pic.rule=Host(`pic.tapoop.com`)"
      - "traefik.http.routers.pic.entrypoints=websecure"
      - "traefik.http.routers.pic.tls.certresolver=leresolver"

networks:
  traefik:
    external:
      name: traefik