global:
  checkNewVersion: false
  sendAnonyMousUsage: false

log:
  level: ERROR
  filePath: /var/log/traefik/error.log
  format: json

api:
  insecure: true
  dashboard: true

ping: {}

accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100
  format: json
  filters:
    minDuration: 10ms

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
  file:
    watch: true
    directory: /etc/traefik/dynamic/
    debugLogGeneratedTemplate: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
tls:
  options:
    default:
      minVersion: VersionTLS12

    mintls13:
      minVersion: VersionTLS13

certificatesResolvers:
  mycrt:
    acme:
      email: devil1990@outlook.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
