providers:
  file:
    directory: /etc/traefik/dynamic/
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
api:
  insecure: true
  dashboard: true

log:
  level: ERROR
  filePath: /var/log/traefik/error.log
  format: json

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: devil1990@outlook.com
      storage: /home/traefik/acme.json
      httpchallenge:
        entryPoint: web
