apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-clone
spec:
  selector:
    matchLabels:
      app: git-clone
  template:
    metadata:
      labels:
        app: git-clone
    spec:
      containers:
      - name: git-clone
        image: hunsh/gh-proxy-py:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-git-clone
spec:
  selector:
    app: myapp
  ports:
  - port: 8081
    targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-git-clone
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`clone.567222.xyz`)
    kind: Rule
    services:
    - name: svc-git-clone
      port: 8081
      namespace: default
  tls:
    certResolver: myresolver