version: '3.9'

services:
  nacos:
    image: nacos/nacos-server:v2.2.0
    container_name: nacos
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./nacos-standlone-mysql.env
    networks:
      - default
networks:
  default:
    name: br0
    external: true
