version: '3.9'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: 'host'
    volumes:
      - /home/jellyfin/config:/config:rw
      - /home/jellyfin/cache:/cache:rw
      - /home/jellyfin/media:/media
    restart: 'unless-stopped'
    environment:
      - TZ=Asia/Shanghai
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096

networks:
  default:
    name: br0
    external: true