version: '3.9'

services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    restart: always
    volumes:
      - ./data:/opt/alist/data:rw
      - ./config.json:/opt/alist/data/config.json:rw
    ports:
      - 5244:5244
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.29
    container_name: mysql
    restart: always
    command:
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 1234qwer
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/conf:/etc/mysql/conf.d:rw
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d:rw
    ports:
      - 3306:3306