version: '3.9'

services:
  ollama:
    iamge: ollama/ollama
    container_name: ollama
    restart: always
    volumes:
      - ./data:/root/.ollama
    ports:
      - 11434:11434
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            capabilities: [gpu]
    networks:
      - default
  
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    volumes:
      - ./open-webui:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 3000:8080
    networks:
      - default
networks:
  default:
    name: nas
    external: true
