version: '3.9'

services:
  casdoor:
    image: casbin/casdoor:latest
    container_name: casdoor
    restart: always
    ports:
      - 8001:8000
    volumes:
      - ./conf:/conf:rw
    networks:
      - demo

networks:
  demo:
    external:
      name: demo