version: '3.9'

services:
  redis:
    image: redis:7.0.9
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./data:/data
    command: redis-server /etc/redis/redis.conf
    networks:
      - default
networks:
  default:
    name: br0
    external: true
