version: '3.9'

services:
  redis:
    image: redis:6.2.7
    restart: always
    container_name: redis
    expose:
      - 6379
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./data:/data
    command: redis-server /etc/redis/redis.conf
    networks:
      default:
        ipv4_address: 172.20.0.3
networks:
  default:
    name: br0
    external: true